server:
  port: 8087
---

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: admin
      username: sjh
      password: sjh
  profiles: default
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: satisfactionhistorymanagement
          destination: pizza
          contentType: application/json
        event-out:
          destination: pizza
          contentType: application/json
#  h2:
#    console:
#      enabled: true
logging:
  level:
#    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8087
---
server:
  port: 8080
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: satisfactionhistorymanagement
          destination: pizza
          contentType: application/json
        event-out:
          destination: pizza
          contentType: application/json
